spring:
  application:
    name: discoveryservice
server:  
  port: ${PORT}
    
eureka:  
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false  
